### ISSUE TITLE
Raspberry Pi?

### ISSUE THREAD

**Issue by s1eve-mcdichae1** [ptitSeb/prototype#3]
> To compile on Pandora, type make
> 
> To compile on ODROID, type make ODROID=1
> 
> To compile on Linux x86, type make LINUX=1

Are any of these compatible with Raspberry Pi?

**Comment by ptitSeb** [comment]
Use the ODROID one, it should work fine.

**Comment by s1eve-mcdichae1** [comment]
Thanks, I'll give it a try.

what are the exact dependencies? I need `libstb-dev`, or...?

and I already have `libsdl2-mixer-dev`. Is that it? Do I need to do something with the `gl4es` package mentioned in the readme?

**Comment by ptitSeb** [comment]
On a Pi3 or Pi4, you already have full opengl with mesa, so gl4es is not needed.
You just need SDL and SDL_mixer, either 1 or 2 depending on the use of `SDL2=1`

**Comment by s1eve-mcdichae1** [comment]
Thank you. It's working well, aside from not being able to pause or exit with the gamepad only (#4).
